# SPDX-FileCopyrightText: 2021 Felipe Lema <felipelema@mortemale.org>
# SPDX-FileCopyrightText: 2022 Nicolás Alvarez <nicolas.alvarez@gmail.com>
# SPDX-License-Identifier: CC0-1.0

variables:
  DEBIAN_FRONTEND: "noninteractive"

clang_format:
  stage: build
  image: debian:testing
  before_script:
    - apt-get update
    - apt-get install --yes --no-install-recommends wget ca-certificates git clang-format-11
    - update-ca-certificates
  script:
    - ./.gitlab-ci.script
  rules:
    - when: manual
      allow_failure: true

include:
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/linux.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/freebsd.yml
